/**
 * 页面按需加载：避免首包打入全部业务页面，进入对应路由再请求 chunk。
 */
import { lazy } from 'react'

export const LoginPage = lazy(() => import('./pages/Login'))
export const ForgotPasswordPage = lazy(() => import('./pages/ForgotPassword'))
export const CompleteEmailPage = lazy(() => import('./pages/CompleteEmail'))
export const DashboardPage = lazy(() => import('./pages/Dashboard'))
export const UserManagementPage = lazy(() => import('./pages/UserManagement'))
export const DingTalkAdminPage = lazy(() => import('./pages/DingTalkAdmin'))
export const DocTasksPage = lazy(() => import('./pages/DocTasks'))
export const DocTasksExcelFormatPage = lazy(() => import('./pages/DocTasksExcelFormat'))
export const ProductsPage = lazy(() => import('./pages/Products'))
export const ConfigOrdersPage = lazy(() => import('./pages/ConfigOrders'))
export const CostListPage = lazy(() => import('./pages/CostList'))
export const ProjectsPage = lazy(() => import('./pages/Projects'))
export const OpportunitiesPage = lazy(() => import('./pages/Opportunities'))
export const OpportunityDetailPage = lazy(() => import('./pages/OpportunityDetail'))
export const ProjectProductListPage = lazy(() => import('./pages/ProjectProductList'))
export const ProjectAnalysisPage = lazy(() => import('./pages/ProjectAnalysis'))
export const LogsPage = lazy(() => import('./pages/Logs'))
export const WorkbenchPushMessagesPage = lazy(() => import('./pages/WorkbenchPushMessages'))
export const ExcelParseRulesPage = lazy(() => import('./pages/ExcelParseRules'))
export const FormulasPage = lazy(() => import('./pages/Formulas'))
export const KnowledgePage = lazy(() => import('./pages/Knowledge'))
export const AutoConfigPage = lazy(() => import('./pages/AutoConfig'))
export const InventoryQueryPage = lazy(() => import('./pages/InventoryQuery'))
export const InventoryMaintainPage = lazy(() => import('./pages/InventoryMaintain'))
export const InventoryStockInPage = lazy(() => import('./pages/InventoryStockIn'))
export const InventoryStockInDetailPage = lazy(() => import('./pages/InventoryStockInDetail'))
export const InventoryStockOutPage = lazy(() => import('./pages/InventoryStockOut'))
export const InventoryStockOutDetailPage = lazy(() => import('./pages/InventoryStockOutDetail'))
export const ConstructionProjectInfoPage = lazy(() => import('./pages/ConstructionProjectInfo'))
export const ConstructionProgressPage = lazy(() => import('./pages/ConstructionProgress'))
export const ConstructionQualityPage = lazy(() => import('./pages/ConstructionQuality'))
export const ConstructionSafetyPage = lazy(() => import('./pages/ConstructionSafety'))
export const ConstructionLogPage = lazy(() => import('./pages/ConstructionLog'))
export const ConstructionProjectDetailPage = lazy(() => import('./pages/ConstructionProjectDetail'))
export const MaintenanceMinorWorkPage = lazy(() => import('./pages/MaintenanceMinorWork'))
export const MaintenanceSchedulePage = lazy(() => import('./pages/MaintenanceSchedule'))
export const ConstructionProgressBulkCreatePage = lazy(() => import('./pages/ConstructionProgressBulkCreate'))
export const StaffHandoverPage = lazy(() => import('./pages/StaffHandover'))
